### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by CottageDwellingCat** [Nexfinity/Fluxer.Net#2]
# [V0.0.1](#1) (The Beginning)
- [x] Heartbeating (need to ask a ditch witch)
- [x] Make *Packet into a unified packet type
- [x] Read messages
- [x] Send messages
- [x] Edit messages
- [x] Sample bot (`/say *`, `/join *`, and `/help` commands)
  - [x] ~~Config file~~
- [x] internal name/type fixes

# V0.0.2 (Socket Snuggles)
- [x] Stable socket connection
  - [x] Resolve weird disconnects
  - [x] Support resuming sessions
- [x] Support ALL known socket events
- [x] Clean the `SqullConnection.cs` file

# V0.0.4 (Basic Functionality)
- [x] Split the client into seperate ApiClient and GatewayClients
- [x] Support ALL known API endpoints
- [x] Add a simple tutorial
  - [x] Make a new example bot
  - [x] With a config file
- [x] Introduce more catches on potential socket errors.

# V0.0.5 (Schema compliance & version matching)
- [x] Match to Squll's OpenAPI schema 

# V0.0.6 (Caching)
- [ ] TBD

# V0.0.7 (Commands)
- [ ] Add a DNet-like command service.

# V0.0.8 (Pre-Release Prep)
- [x] Setup README for repo
- [x] Setup Nuget feed CI/CD
- [x] Finalize the docs website & provide updated examples

# V1.0.0 (Public Release Candidate)
- [x] TBD

# V1.1.0 (Extended Functionality)
- [ ] Add new Squll features (TBD)
